export type Recipe = {
    id: string,
    userId: string,
    title: string,
    description: string,
    ingredients: string[],
    instructions: string[],
    cookingTime: number,
    servings: number,
    difficulty: 'easy' | 'medium' | 'hard',
    rating: number,
    isPublic: boolean,
    imageURL: string,
    createdAt?: string // delete later because generated by db
}

export type BodyRecipe = {
    title: string,
    userId: string,
    description: string,
    ingredients: string[],
    instructions: string[],
    cookingTime: number,
    servings: number,
    isPublic: boolean,
    imageURL: string,
    difficulty: 'easy' | 'medium' | 'hard',
    rating: number,
}

export type User = {
    id: string,
    username: string,
    email: string,
    firstName: string,
    lastName: string,
}

export type BodyUser = {
    username: string,
    email: string,
    password: string,
    firstName: string,
    lastName: string,
}

export type DbUser = {
    id: string,
    username: string,
    email: string,
    password: string,
    firstName: string,
    lastName: string,
    createdAt: string,
    updatedAt: string | null
}

export type Credentials = {
    email: string,
    password: string
}

export type RequestUser = {
    id: string,
    email: string
    username: string
}

export type CommentBody = {
    recipeId: string,
    userId: string,
    username: string
    comment: string,
    rating: number
}

// add user to express request object
declare global {
    namespace Express {
        interface Request {
            user?: RequestUser
        }
    }
}
